### ISSUE TITLE
Train_bow aborted when reached 10000 papes

### ISSUE THREAD

**Issue by LiuYuLOL** [wetneb/opentapioca#16]
Hi, I just found this great entity linking work and am extremely excited to use it on my own data. 

However, it returned to aborted! when I train the language model using ``tapioca train-bow latest-all.json.bz2``

The error information is following:
> (myenv) myuser@myserver:~/tools/opentapioca$ tapioca train-bow latest-all.json.bz2
> 0
> 10000
> 
> Aborted!

Actually, I met another error before this one. When I run `bin/solr zk -upconfig -z localhost:9983 -n tapioca -d configsets/tapioca` directly without any modification, I got 

> ERROR - 2020-04-14 11:24:50.649; org.apache.solr.util.SolrCLI; Could not complete upconfig operation for reason: Could not find solrconfig.xml at /home/uqyliu42/tools/solr-7.7.2/server/solr/configsets/solrconfig.xml, /home/uqyliu42/tools/solr-7.7.2/server/solr/configsets/conf/solrconfig.xml or /home/uqyliu42/tools/solr-7.7.2/server/solr/configsets/configsets/tapioca/conf/solrconfig.xml

So I copy the fold ~/tools/opentapioca/configsets  into ~tools/solr-7.7.2/server/solr/configsets/ and run again. Got:
> Uploading /home/uqyliu42/tools/solr-7.7.2/server/solr/configsets/configsets/tapioca/conf for config tapioca to ZooKeeper at localhost:9983

I think I successfully uploaded the configsets. But why solr fails to index the Wikidata Json?

**Comment by wetneb** [comment]
Thanks for reporting this! I am curious about the abort, I have not encountered it myself. Do you perhaps have memory limitations which could cause this? Do you have a way to raise the memory limit for processes, perhaps?

**Comment by LiuYuLOL** [comment]
That's weird, I think there is sufficient memory. I use `htop` to see the change of memory. From 0 to 10000, it only increased by 0.2 Gbytes. Then it aborted. The server at least has 30 Gbytes free memory.

**Comment by LiuYuLOL** [comment]
Got fixed! by deleting all and re-installing solr and tapioca.
