### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by valevo** [wetneb/opentapioca#18]
Hi,

first of all, thank you very much for openly providing this service!
The /annotate endpoint started resulting in internal server errors since about a week ago. Similarly, the /nif endpoint seems to ignore queries by responding with an empty list of annotations. 
Is this project still being maintained and so will this be fixed? Or can I take this as a sign that the service is being taken down?
Thanks!

**Comment by wetneb** [comment]
@valevo thanks for reporting this! I have just restarted the service.

**Comment by valevo** [comment]
Much appreciated! Back to entity linking :)
