### ISSUE TITLE
Dealing with non-lemmatized versions of entities

### ISSUE THREAD

**Issue by lighteternal** [wetneb/opentapioca#28]
Hi and congrats for this excellent work! 

I wish to use Opentapioca as part of an infomation extraction pipeline to perform entity linking of extracted triples (subj-pred-object) with Wikidata entities in Greek. 
After a few preliminary tests, Opentapioca seems to be able to recognize Greek entities in their lemmatized form. 
For example "Αθήνα" (Greek for Athens) is linked with Q1524. 

However, Greek nouns and verbs have declension, accentuation and conjugation, so it's common to find them in forms others than their basic (e.x. Αθηνα, Αθήνας, Αθηνών) etc.  An obvious workaround would be to use a lemmatizer (e.g. Spacy) to convert them to their lemmatized form before applying the Opentapioca EL. However this doesn't work in practice since the Greek lemmatizer is not that efficient, plus it returns the entities lower-cased. 

As I was digging through your implementation, I was wondering if there is any parametrization (e.g. similarity threshold) or fuzzy method that would allow for non-lemmatized words to be linked with the Wikidata entities (ideally with a confidence score). 

Many thanks for your time on reading this! :D

**Comment by wetneb** [comment]
When using your lemmatizer, did you apply it manually upstream or did you add it in the Solr indexing pipeline? I think the latter might give you better results, since it would be applied both to your input text and to the Wikidata labels. The fact that your lemmatizer returns entities in lowercase should not be a big issue as long as it is applied to both the input text and the Wikidata labels.

I thought the Solr text tagger had some options to match up to some distance, but I cannot find it anymore. I think all you can do with this architecture is tweak the analysis pipeline to add more normalization steps, which result in some controlled fuziness.

**Comment by lighteternal** [comment]
I applied it manually on my text before querying Solr. Your tip on applying it on the indexing pipeline makes more sense though, thanks!

I was searching for a "partial match" solution for the Solr text tagger after your response, and it seems that others have similar questions and proposing some config workarounds (e.g. https://hls-consulting.com/2019/10/09/solr-partial-match-is-not-working-on-computed-field-why/ or the ngram tokenizer: https://lucene.apache.org/solr/guide/6_6/tokenizers.html#Tokenizers-EdgeN-GramTokenizer) 
Being a Solr newbie, I have to learn what to modify in order to make it work :). 

It's a bit surprising though that there's not a simple  distance-based (e.g. Levenshtein) method to return partial matches (although this could get really computationally expensive if it has to run on demand for every query). 


I alsochecked this part:
```
class SimpleTagClassifier(object):
    """
    A linear support vector classifier to predict the validity of a tag in a mention.
    """
    def __init__(self, tagger, beta=0.85, nb_steps=2, C=0.001, max_similarity_distance=100, similarity_smoothing=0.1, similarity="direct_link"):
        self.tagger = tagger
        self.beta = beta
        self.nb_steps = nb_steps
        self.C = C
        self.identifier_space = 'http://www.wikidata.org/entity/'
        self.similarity = similarity
        self.max_similarity_distance = max_similarity_distance
        if similarity == "direct_link":
            self.similarity_method = DirectLinkSimilarity()
        elif similarity == "edge_ratio":
            self.similarity_method = EdgeRatioSimilarity()
        else:
            self.similarity_method = OneStepSimilarity(beta)
        self.similarity_smoothing = similarity_smoothing
```
Maybe changing the default _direct link_ similarity with another measure (or adjusting m_ax_similarity distance_)would make it work...?

**Comment by wetneb** [comment]
No, those similarity methods are doing something different: they compute the similarity between two different candidate items for neighbouring phrases in the text.

The section you want to modify is here:
https://github.com/wetneb/opentapioca/blob/2c060fb12afc6854e18e16e2b9a18ddca42fe2fb/configsets/affiliations/conf/managed-schema#L63-L77

I would try to add a greek lemmatizer in this section (both in the `index` and `query` sections, at the same position). Of course you will need to re-upload the configset to Zookeeper and reindex your collection after that.

**Comment by lighteternal** [comment]
Great! Many thanks for your quick and helpful response! Closing this for now! ❤️
