### ISSUE TITLE
Adding Opentapioca to GERBIL

### ISSUE THREAD

**Issue by rhoi2021** [wetneb/opentapioca#38]
Hello,
One question, has Opentapioca been added to GERBIL or r u going to do it?

**Comment by wetneb** [comment]
Hi!
When going to http://gerbil.aksw.org/gerbil/config I can see OpenTapioca there already:
![image](https://user-images.githubusercontent.com/309908/125276418-7a8d6200-e310-11eb-8951-5051914187ac.png)
Is there anything else I should be doing?
