### ISSUE TITLE
Is it possible to get other properties such as "Parent Organization" P749

### ISSUE THREAD

**Issue by stephenleo** [wetneb/opentapioca#42]
Is it possible to also return the results from some other properties in a query like this? 
For example, many organizations have parent organization property (P749): https://www.wikidata.org/wiki/Property:P749

```
curl 'https://opentapioca.org/api/annotate'  --data 'query=Associated+Press+writer+Julie+Pace+contributed+from+Washington.'
```

**Comment by wetneb** [comment]
Those are not available from tapioca itself, you will need to query wikidata directly for that.
