### ISSUE TITLE
train-classifier data

### ISSUE THREAD

**Issue by senisioi** [wetneb/opentapioca#49]
[Pre-trained dumps](https://github.com/wetneb/opentapioca/releases/tag/v0.1.0) are greatly helpful, but which NIF dataset has been used to train the classifier that is running on the online demo?
The paper [clarifies this](https://arxiv.org/pdf/1904.09131.pdf#page=7), but it's not entirely clear where one could download this dataset from to train the classifier locally.

Thanks for all the work!

**Comment by wetneb** [comment]
I think it is [merged_RSS-500_and_istex_train.ttl](https://github.com/wetneb/opentapioca/blob/master/data/merged_RSS-500_and_istex_train.ttl), in the `data` directory of this repository.

**Comment by senisioi** [comment]
Thanks, it's much appreciated.
