### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by debayan** [wetneb/opentapioca#7]
Hi

Is there a web api I can hit? I see there is a NIF api but I do not know how to access it.

**Comment by wetneb** [comment]
At the moment only the NIF API is officially exposed, but if you use your browser's inspector you will see that the web UI does POST requests to the backend with a simple JSON-based API, you can imitate that :)

**Comment by debayan** [comment]
Thanks a lot, I was able to get the json endpoint working. Hit it with 6k questions from lc-quad 2.0 test set http://lc-quad.sda.tech/

**Comment by LiuYuLOL** [comment]
I just use `requests to post a query, and got 403 returns.

>  URL = "https://opentapioca.org/api/annotate"
    text = {'text': "Associated Press writer Julie Pace contributed from Washington."}
    r = requests.post(url=URL, json=text) 

Am I in the right way? How to fix it? Besides, can I use the API parse large dataset, e.g. 10 Gbytes?

**Comment by wetneb** [comment]
The server is quite small so it will probably not like it if you hit it with 10 Gbytes of text…
To figure out the API format, just inspect what queries are done by the web frontend using your web browser.

**Comment by LiuYuLOL** [comment]
> The server is quite small so it will probably not like it if you hit it with 10 Gbytes of text…
> To figure out the API format, just inspect what queries are done by the web frontend using your 

Yes, the volume seems too huge and could run weekly. Fortunately, I can run a local server with your provided models. However, I still stuck in the API format where the inspected page is like following

<img width="1386" alt="Screen Shot 2020-04-15 at 5 37 14 pm" src="https://user-images.githubusercontent.com/23356317/79311222-740f0f80-7f40-11ea-813d-79fff5e99972.png">

**Comment by LiuYuLOL** [comment]
Sorry for bothering you again.

Is it possible to run multiple `tapioca` servers? I want to speed up the data processing as the volume is huge.  So in my mind, I want to split the data and feed them separately into different servers.

There are some questions. For example, 
- Does `Solr` limit the performance as tapioca will search Solr index? If so, can I run multiple Solrs?
- Can I run the whole things, using `python.multiprocessing` , e.g, pool?
- Do you have any suggestions to facilitate the processing?

**Comment by wetneb** [comment]
See Solr's manual to scale Solr to multiple nodes. You can run multiple tapioca frontends too.
