### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/xxx/opentapioca/README.rst'

### ISSUE THREAD

**Issue by heathersherry** [wetneb/opentapioca#8]
Dear authors,

Thanks for sharing this great project!

When I tried to install the CLI in my path using `python setup.py install`, I came across this error:

> Traceback (most recent call last):
>   File "setup.py", line 17, in <module>
>     with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
>   File "/usr/lib/python2.7/codecs.py", line 898, in open
>     file = __builtin__.open(filename, mode, buffering)
> IOError: [Errno 2] No such file or directory: '/xxx/opentapioca/README.rst'

May I ask how to solve this issue? Thanks a lot for your help!

**Comment by wetneb** [comment]
Hi,

OpenTapioca requires Python 3 and you seem to be using Python 2.

**Comment by heathersherry** [comment]
Hi,

Thanks for the prompt reply.
I have tried both Python 2 and Python 3, and it seems to have the same problem.

```
xxx@Ubuntu-P100-2:/xxx/opentapioca$ python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
  File "/usr/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/xxx/opentapioca/README.rst'
```
Did I make some mistake here?

**Comment by heathersherry** [comment]
Hi,

I fixed this issue by replacing `README.rst` to `README.md`. Maybe it is better to change in the project as well?
Thanks a lot for sharing this project again.
